[project]
name = "blockpost"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.blockpost]
path = "contracts/blockpost.clar"
depends_on = []
